# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89ecca87553284e2abb911cb46ac2a0c6994c2307b0f9a35bc65446a00563551f8900332767b64be250fd19921dcb9c107a76aa6c0dc5533691adf35a0980206

test:
  secret_key_base: 2b163695101ebe7cbf0194abc00628566b896ef1bc605f7faeb3ae2b0643bc86fb8597af650b09e6e0662482b5bf54230dcd7ca6d2160085031fa82e1a6ef6cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
